length=float(input("Enter the length of the rectangle: "))
breadth=float(input("Enter the breadth of the rectangle: "))
area=round(length*breadth, 3)
perimeter=round(2*(length+breadth), 3)
print(f"The perimeter of the rectangle is: {perimeter}cm")
print(f"The area of the rectangle is: {area}cm²")