price=float(input("Enter the price: "))
percent_discount=float(input("Enter the percent discount: "))
print(f"{price}: {price:.2f}")
print(f"{percent_discount}% discount: {percent_discount:.1f}%")
print(f"{price}: {price:03}")
print(f"{price}: {price:<03}")
print(f"{price}: {price:>08}")
print(f"{price}: {price:^08}")
print(f"{price}: {price:+.2f}")
print(f"{-price}: {-price:+.2f}")
print(f"{price}: {price:,.1f}")
