set1=set()
num_ele=int(input("Enter number of elements you want to add in the set: "))
for i in range(num_ele):
    ele=input("Enter element {}: ".format(i+1))
    set1.add(ele)
print("Original Set: ", set1)
add_ele=input("Enter an element to add to the set: ")
set1.add(add_ele)
print("Set after adding element: ", set1)
print("Sorted Set: ", sorted(set1))
print("Set after removing an arbitrary element: ", set1.pop())
print("Final Set: ", set1)
set2=set()
num_ele2=int(input("Enter number of elements you want to add in the second set: "))
for i in range(num_ele2):
    ele2=input("Enter element {}: ".format(i+1))
    set2.add(ele2)
print("Second Set: ", set2)
print(f"Union of set1: {set1} and set2: {set2} is: {set1.union(set2)}")
print(f"Intersection of set1: {set1} and set2: {set2} is: {set1.intersection(set2)}")
print(f"Difference of set1: {set1} and set2: {set2} is: {set1.difference(set2)}")
print(f"Difference of set2: {set2} and set1: {set1} is: {set2.difference(set1)}")
print(f"Symmetric Difference of set1: {set1} and set2: {set2} is: {set1.symmetric_difference(set2)}")
print(f"Is set1: {set1} a subset of set2: {set2}? : {set1.issubset(set2)}")
print(f"Is set1: {set1} a superset of set2: {set2}? : {set1.issuperset(set2)}")   
print(f"Are set1: {set1} and set2: {set2} disjoint? : {set1.isdisjoint(set2)}")
print("Clearing all elements from set1.")
set1.clear()
print("Set1 after clearing: ", set1) 
print("Set2 remains unchanged: ", set2)