s = {1, 2, 3}
print(f"Initial set: {s}")
s.add(4)
print(f"Set after adding 4: {s}")
s.add(4)
print(f"Set after adding 4 again: {s}")
s.remove(2)
print(f"Set after removing 2: {s}")
s.discard(5)
print(f"Set after discarding 5 (not present): {s}")
s.discard(3)
print(f"Set after discarding 3: {s}")
s.add(2)
s.add(3)
print(f"Set after adding 2 and 3 back: {s}")
s.pop()
print(f"Set after popping an element: {s}")
s.clear()
print(f"Set after clearing all elements: {s}")